title: Lucas Maes
plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
remote_theme: jekyll/minima
minima:
  skin: classic
  social_links:
    twitter: lucasmaes_
    github:  lucas-maes
    youtube_channel: UCnxmN17O2Z2zFESEJsHOW5w
    youtube_channel_name: Lucas Maes
google_analytics: G-NGQWNXRS74
highlighter: rouge
kramdown:
    math_engine: katex
    syntax_highlighter: rouge
